### ISSUE TITLE
Cannot setup watch for multiple gpios watch_gpio 

### ISSUE THREAD

**Issue by urbanskimichal** [iiot2k/gpiox#3]
Watching single gpio using watch_gpio works fine, but when I try to setup watch for multiple gpios, like for example:

```
gpiox.watch_gpio(14, gpiox.GPIO_MODE_INPUT_PULLUP, 100, gpiox.GPIO_EDGE_RISING, (state, edge, pin) => {
    console.log('pressed: ' + pin);
});

gpiox.watch_gpio(15, gpiox.GPIO_MODE_INPUT_PULLUP, 100, gpiox.GPIO_EDGE_RISING, (state, edge, pin) => {
    console.log('pressed: ' + pin);
});
```
only the callback for the latter is called. Nothing happens when i press a button on pin 14, and when i press a button on pin 15, the callback is executed.

I am using Raspberry Pi 5

**Comment by iiot2k** [comment]
The problem is described in issue 1.
