### ISSUE TITLE
Service Node-RED exited with code 256 (by signal 11)

### ISSUE THREAD

**Issue by guenter-ms** [iiot2k/gpiox#5]
Hello, 

Node-Red crashes after installation of @iiot2k/node-red-gpiox and enters boot-loop, see protocol.

Nodered is running as an app under Homeassistant on a raspy 4B.

Any idea?

![Bildschirmfoto 2024-09-19 um 17 26 31](https://github.com/user-attachments/assets/7f8043ac-043b-40f9-a360-f1bda86abc0e)

**Comment by iiot2k** [comment]
Homeassistant disables GPIO Support:
https://github.com/home-assistant/architecture/blob/780ea1b180263fce7b08805c019dd580f3db6fe2/adr/0019-GPIO.md
